# Generated by Django 3.2.5 on 2021-07-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(
                    help_text='Enter your first name', max_length=50)),
                ('last_name', models.CharField(
                    help_text='Enter your second name', max_length=50)),
            ],
        ),
    ]
