# Generated by Django 3.2.5 on 2021-07-31 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SampleNames',
            new_name='SampleName',
        ),
    ]
